version: "3.8"
services:
  frontend:
    image: node:18.8.0-bullseye
    restart: "no"    
    build:
      context: ./frontend
      dockerfile: Dockerfile
      tags:
      - parcellab-frontend
    env_file:
      - ".env"
    volumes:
      - ./frontend:/app
    command: >
      bash -c "yarn && yarn build"


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["rails", "server", "-b", "0.0.0.0"]
    env_file:
      - ".env"
    restart: "no"
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - ./frontend/build:/app/public

  postgres:
    image: postgres:12.11-alpine
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

volumes:
  postgres-data:  